Add Accordion titles and heading levels
ccswbs/gus pull request #141
Opened 2023-06-07 20:40 UTC by tqureshi-uog

# Summary of changes
Content editors now have the ability to add a title for an `Accordion` widget and set its heading level. They can also set the heading level for each `Accordion` item title.

## Frontend
- Add new fields to `gatsby-node.js` schema
- Add accordion title and heading level to `accordion.js`
- Add accordion item titles and heading levels to `accordion.js`

### Incidental changes
- Reduce top margin on `Section` widget title in `widget.js`
- Upgrade packages (keeps this repo in sync with `doorknob`)

## Backend
- Add optional title field and heading level to `Accordion` paragraph type
- Add optional heading level field to `Accordion Item` title
- Update relevant field labels and instructions

# Test Plan

Gatsby Cloud site: https://tqtest.gatsbyjs.io/accordion-test/
Drupal multidev: https://accordionh-chug.pantheonsite.io/

1. Go to https://tqtest.gatsbyjs.io/accordion-test/ and confirm all headings are nested properly

2023-06-08 18:24 UTC, abanuog commented
For the heading level dropdown, can you set the default to h2 (instead of none), and remove none, since it's not really an option ?

2023-06-08 18:31 UTC, tqureshi-uog commented
> For the heading level dropdown, can you set the default to h2 (instead of none), and remove none, since it's not really an option ?

The default is already set to h2:

![image](https://github.com/ccswbs/gus/assets/13698158/3c102c10-9c2a-4f3e-ae68-0fb33775cea6)

...but it will only take effect for new content (you can test this by going to https://accordionh-chug.pantheonsite.io/node/add/page and adding an `Accordion` widget). On existing accordion widgets, the setting will default to `None`

2023-06-08 19:52 UTC, mmafe reviewed
Added a code snippet for shortening one segment. 

Other than that, nesting works like a dream.

Only thought is that occasionally it looks like users have been adding a class <text-dark> to make the heading above the accordion dark. That will no longer be an option for users, however I don't think it should be an option (and the h3s are going to be dark anyway in future, so that'll eventually sort itself out.)

2023-06-08 19:52 UTC, mmafe commented on src/components/shared/accordion.js
> +              let headingElement;
Try replacing lines 31 through 53 with the following:

```
              let HeadingLevelItem = (
                (item?.field_heading_level === "h3" || item?.field_heading_level === "h4") 
                ? item.field_heading_level : "h2");

              let headingElement = (
                <HeadingLevelItem className="accordion-header" id={"heading" + item.drupal_id}>
                  {accordionToggle}
                </HeadingLevelItem>
              )
``` #

2023-06-08 20:23 UTC, mmafe commented on src/components/shared/accordion.js
> +              let headingElement;
This comment is resolved with the latest update.

2023-06-08 20:25 UTC, mmafe requested changes
As discussed on Teams, we are adding an h5 and h6 option to the Accordion Item on the Drupal side. Will review one more time after that occurs.

2023-06-08 20:45 UTC, tqureshi-uog commented
> As discussed on Teams, we are adding an h5 and h6 option to the Accordion Item on the Drupal side. Will review one more time after that occurs.

Done.

2023-06-12 15:24 UTC, mmafe approved these changes

2023-06-12 15:26 UTC, snschau approved these changes

2023-06-12 16:13 UTC, merged