Addheading
ccswbs/gus pull request #161
Opened 2023-10-18 18:12 UTC by ovcwcoop

# Summary of changes
Brief description of the proposed changes
Added an option in the Section Widget to change the heading level that will be displayed for the section title. Defaults to h2 if no choice is selected, and otherwise allows for headings to be used from h2-h6. 
## Frontend
List all significant changes to Gatsby code

## Backend
List all significant changes to the Drupal site (e.g. new fields, content types, modules, etc)

# Test Plan

Insert steps. Include URLs of Gatsby Cloud test site and Drupal multidev.

2023-10-19 17:43 UTC, snschau commented
https://deploy-preview-161--mp-gus-test.netlify.app/ for this worked after a couple of retrys - was failing due to timing out.

2023-10-20 20:21 UTC, tqureshi-uog requested changes

2023-10-20 20:21 UTC, tqureshi-uog commented on src/components/shared/widget.js
> +            let HeadingLevelSec = (widget.field_heading_level ? widget.field_heading_level : "h2");
This is where you could add logic to check if heading_level is h5 or h6, and if so, assign it a value of "h4" instead

2023-10-25 16:19 UTC, snschau approved these changes

2023-10-26 16:23 UTC, merged