404 jk
ccswbs/gus pull request #168
Opened 2023-10-30 17:26 UTC by ljairath

# Summary of changes

Updated 404 page. See [PRODUCT BACKLOG ITEM 70298](https://dev.azure.com/uoguelph/CCS/_workitems/edit/70298)

## Frontend

1. Updated email to websites@uoguelph.ca
2. Add U of G search page link
3. Updated page content on 404 page

[x ] My changes are accessible (at minimum WCAG 2.0 Level AA)
[x ] My changes are responsive and appear as expected on mobile and desktop views.
[NA] After merging, I will update the [Content Hub documentation](https://uoguelphca.sharepoint.com/sites/UniversityContentHubInformationGroup) and ensure the Content Hub trainer understands how my changes will affect users.

## Backend
- NA

# Test Plan
- Request any content that does not exist on the U of G website CH 

Insert steps. Include URLs of Netlify test site and Drupal multidev.

2023-10-30 18:09 UTC, RazaMM requested changes

2023-10-30 18:09 UTC, RazaMM commented on src/pages/404.js
> +              <a href="https://www.uoguelph.ca/search">Search on the University of Guelph</a>
Can we make it so this link has the search bar automatically filled out to the page that wasn't found?

For example if the user went to https://www.uoguelph.ca/cows they could click "Search on the University of Guelph" and the search bar would have "cows" already filled in.

The search page does allow for the url to fill the search bar ex. navigating to https://www.uoguelph.ca/search/#gsc.tab=0&gsc.q=webadvisor&gsc.sort= will have webadvior filled in the search bar

2023-10-30 18:09 UTC, RazaMM commented on src/pages/404.js
> +                The university has removed this page (either by purpose or by mistake) - <a href="mailto:websites@uoguelph.ca">please let us know!</a>
Change the wording here: 

either by purpose 

to

either on purpose

2023-11-01 13:31 UTC, RazaMM approved these changes

2023-11-01 14:08 UTC, merged

2023-11-01 14:08 UTC, ljairath commented
updated 404 page for the CH