[DRAFT] Let content authors add files via the WYSIWYG editor
ccswbs/gus pull request #217
Opened 2024-04-01 16:21 UTC by tqureshi-uog

# Summary of changes
Minimum Viable Product version of https://dev.azure.com/uoguelph/CCS/_workitems/edit/74912/ - content authors can now insert files via the existing Linkit tool and no longer have to manually copy and paste absolute links. These links are then processed by an enhanced text-parsing function to start with the correct base URL.

## Frontend
- Add media file to schema in `gatsby-node.js`
- Create `AnchorTag` function to process links, detecting if link is of type "media" and prepending the appropriate Drupal base URL
- Refactor `generalText.js` to move all text-processing functions to `ug-utils.js`
- Refactor `ug-utils.js` to use alphabetical ordering for functions and remove obsolete/unused code
- Use the new text-parsing functions in `accordion.js`, `mediaText.js` and `pageTabs.js`

### Spring Cleaning
- Remove unused `footer.js` component (not needed since we use the web components version)
- Remove unused `newsGrid.js` and `grid.js` components (leftovers from long-abandoned original program page template)
- Remove unused `navTabs.js` component and related files (this was replaced by pageTabs.js` some time ago)
- Remove unused `relatedPages.js` component
- Remove unused `sidebar.js` component
- Remove calls to obsolete and unnecessary `contentExists` function from the following files:
    - `footerOVC.js`
    - `heroVideo.js`
    - `stats.js`
- Delete `contentExists` function from `ug-utils.js`

[ x ] My changes are accessible (at minimum WCAG 2.0 Level AA)
[ x ] My changes are responsive and appear as expected on mobile and desktop views.
[ x ] After merging, I will update the [Content Hub documentation](https://uoguelphca.sharepoint.com/sites/UniversityContentHubInformationGroup) and ensure the Content Hub trainer understands how my changes will affect users.

## Backend
In progress - see [this message](https://teams.microsoft.com/l/message/19:f2ae5b00dc95407d8902b0e04ff98ec1@thread.tacv2/1711484549308?tenantId=be62a12b-2cad-49a1-a5fa-85f4f3156a7d&groupId=cde949b1-e9d8-483b-8d20-e9b8fd9e493d&parentMessageId=1711484549308&teamName=Content%20Hub%20Team&channelName=Multidev%20Merge%20Requests&createdTime=1711484549308&allowXTenantAccess=false)  for details

# Test Plan

## Known issues
- The `AnchorTag` function as written cannot handle edge cases where an anchor tag has inline styles so instead it strips them out and leaves the rest of the link intact. Since inline styles are strongly discouraged anyway and break accessibility rules, we could leave this as-is.

2024-04-02 18:33 UTC, mmafe requested changes
Something odd is occurring to the spacing. I think the change is significant enough that it'll be noticeable if we release as is.

https://deploy-preview-217--ugconthub.netlify.app/oac/study/plants/
![image](https://github.com/ccswbs/gus/assets/1927902/9514df73-c226-46d4-9d3a-37acfcc34480)

![image](https://github.com/ccswbs/gus/assets/1927902/c9b28369-3c07-4c89-8037-5324edff70d2)

2024-04-02 20:00 UTC, tqureshi-uog commented
> Something odd is occurring to the spacing. I think the change is significant enough that it'll be noticeable if we release as is.
> 

This is because of poorly thought-out spaghetti code in UofG-styles-dist.css - it has a rule applying a margin-top value of 3rem to heading levels h1 - h6, but that rule gets overridden in certain situations by the following Bootstrap default:

```
.row>* {
    flex-shrink: 0;
    width: 100%;
    max-width: 100%;
    padding-right: calc(var(--bs-gutter-x)* .5);
    padding-left: calc(var(--bs-gutter-x)* .5);
    margin-top: var(--bs-gutter-y);
}
```

For some reason, the value used by UofG-styles-dist.css for `--bs-gutter-y` has been set to 0 and this in turn overrides the top margin value for any heading elements that are direct children of divs with the `row` class. We didn't see this problem before because the original generalText.js code added an extra div like so:

```
<div class="row">
  <div>
    <h3>Heading 1</h3>
  </div>
</div>
```

...whereas this PR gets rid of the extra div:

```
<div class="row">
    <h3>Heading 1</h3>
</div>
```
It should also be noted this glitch only applies to General Text widgets in sections because of this (original code, unchanged by this PR):

```
<ConditionalWrapper
      condition={secondary.length > 0}
      wrapper={(children) => <div className={classNames("row", gridClasses)}>{children}</div>}
>
```
We could restore the extraneous div, but I feel it's cleaner to add a new CSS rule to prevent the problem:

```
.row > h1,
.row > h2,
.row > h3,
.row > h4,
.row > h5,
.row > h6 {
    margin-top: 3rem !important;
}
```

2024-04-03 17:39 UTC, RazaMM approved these changes

2024-04-03 17:54 UTC, mmafe approved these changes

2024-04-04 14:54 UTC, merged