Dvmapply
ccswbs/gus pull request #97
Opened 2022-06-28 13:36 UTC by snschau

# Summary of changes
add some yamil block code for section images.

## Frontend
- add dvm-application-offers.js, dvm-application-process.js, dvm-application-requirements.js, and dvm-application-selection.js to add the images. 

## Backend
- none

# Test Plan

Insert steps. Include URLs of Gatsby Cloud test site and Drupal multidev.

https://sstest.gatsbyjs.io/dvm-program-application - should have 4 full width images/with text overlay

2022-06-28 17:08 UTC, mmafe requested changes

2022-06-28 17:08 UTC, mmafe commented on src/components/blocks/ovc/heading-layout.js
> +import React from "react"
Should this file be part of the PR?

2022-06-28 17:08 UTC, mmafe commented on src/components/blocks/ovc/dvm-application-offers.js
> +import React from "react"
It looks like all four components could be accomplished with one component. Recommend having one block component called dvm-application.js, then pass the colourOptions and icon (i.e., fa-circle-1) as variables in yamlWidget.js.

2022-06-28 17:13 UTC, mmafe commented on src/components/shared/yamlWidget.js
> +        'dvm_application_selection':<DVMApplicationSelection />,
```suggestion
        'dvm_application_selection':<DVMApplication colourOptions={background: "var(--uog-yellow)", colour: "#000000"} icon="fa-circle-3" />,
```

Example of passing variable through to component

2022-06-28 17:25 UTC, mmafe requested changes

2022-06-28 17:25 UTC, mmafe commented on src/components/blocks/ovc/dvm-application-selection.js
> +export default function DVMApplicationSelection() {
```suggestion
export default function DVMApplication (props) {
```
Example if we changed this file to dvm-application.js and passed props to component

2022-06-28 17:25 UTC, mmafe commented on src/components/blocks/ovc/dvm-application-selection.js
> +  return <StaticQuery query={query} render={({blockContentYamlBlock}) => render(blockContentYamlBlock, colourOptions)} />
```suggestion
  return <StaticQuery query={query} render={({blockContentYamlBlock}) => render(blockContentYamlBlock, props.colourOptions, props.icon)} />
```

2022-06-28 17:25 UTC, mmafe commented on src/components/blocks/ovc/dvm-application-selection.js
> +                  <p className="display-2 text-dark"> <i class="fa-light fa-circle-3 fa-lg"> </i> <strong>{yamlMap.title}</strong></p>
```suggestion
                  <p className="display-2 text-dark"> <i className=`fa-light {props.icon} fa-lg`> </i> <strong>{yamlMap.title}</strong></p>
```

2022-06-28 17:25 UTC, mmafe commented on src/components/blocks/ovc/dvm-application-process.js
> +const colourOptions = {background: "var(--uog-red)", colour: "#ffffff"};
Is this variable being used? If not, then we could just pass in the icon.

2022-07-04 17:42 UTC, snschau commented
will have to go with individual files - as each of these references a different yaml block in drupal - thus, have different images and headings.  The differences are not just style (as in the international pages for talk to a student).

2023-09-28 19:23 UTC, closed without merging